"""added_new_tables_and_updated_the_old_ones

Revision ID: 356ecfcdccad
Revises: b7b4b3753911
Create Date: 2026-02-25 21:06:46.800443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356ecfcdccad'
down_revision: Union[str, None] = 'b7b4b3753911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_of_reward',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name_of_reward', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('link_on_photo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issuance_of_rewards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('reward_id', sa.BigInteger(), nullable=True),
    sa.Column('name_of_reward', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('moderator_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['catalog_of_reward.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_applications', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('users', 'direction')
    op.drop_column('users', 'email')
    op.drop_column('users', 'institute')
    op.drop_column('users', 'course')
    op.drop_column('users', 'group')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'start_year')
    op.drop_column('users', 'end_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('end_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('start_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('institute', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'username')
    op.drop_column('event_applications', 'username')
    op.drop_table('issuance_of_rewards')
    op.drop_table('catalog_of_reward')
    # ### end Alembic commands ###
