"""remove role_id from event_applications

Revision ID: b7b4b3753911
Revises: fc7d589d2a63
Create Date: 2026-01-12 13:33:39.339331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b4b3753911'
down_revision: Union[str, None] = 'fc7d589d2a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_applications_role_id_fkey'), 'event_applications', type_='foreignkey')
    op.create_foreign_key(None, 'event_applications', 'users', ['tg_id'], ['tg_id'])
    op.drop_column('event_applications', 'role_id')
    op.add_column('roles', sa.Column('base_value_tiukoins', sa.Float(), nullable=False))
    op.drop_column('roles', 'base_value_tiucoins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('base_value_tiucoins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('roles', 'base_value_tiukoins')
    op.add_column('event_applications', sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_applications', type_='foreignkey')
    op.create_foreign_key(op.f('event_applications_role_id_fkey'), 'event_applications', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
