from .bot_config import config
from .moderator_topics import *

__all__ = [
    "config",
    "TOPIC_ADMIN_PANEL",
    "TOPIC_SUPPORT", 
    "TOPIC_SOCIAL_DESIGN",
    "TOPIC_RESEARCH_TECHNOLOGIES",
    "TOPIC_SEARCH_RESCUE_MILITARY",
    "TOPIC_ENTREPRENEURSHIP",
    "TOPIC_PATRIOTISM_HISTORY",
    "TOPIC_INTELLECTUAL_GAMES",
    "TOPIC_TIU_COMPETENCE_CENTER",
    "TOPIC_SCENIC_CREATIVITY",
    "TOPIC_APPLIED_CREATIVITY",
    "TOPIC_MEDIA_COMMUNICATIONS",
    "TOPIC_VOLUNTEERING",
    "TOPIC_ECOLOGY_NATURE",
    "TOPIC_SPORT",
    "TOPIC_TOURISM_TRAVEL",
    "TOPIC_DIGITAL_SPORT",
    "TOPIC_STUDENT_UNITS",
    "TOPIC_UNITED_STUDENT_COUNCIL",
    "TOPIC_HEADMAN",
    "TOPIC_REGISTRATION_NEW_USER",
    "GENERAL_CHAT",
    "USER_FEEDBACK",
    "ISSUANCE_OF_INCENTIVES"
]
