LEXICON_USER_KEYBOARD = {
    "submit_application": "📝 Подать заявку",
    "my_tyuiu_coins": "💎 Мои ТИУкоины",
    "catalog_of_rewards": "📖 Каталог поощрений",
    "agreement_of_contest": "ℹ️ О конкурсе",
    "support": "❓ Поддержка",
    
    "balance_coins": "💎 Баланс ТИУкоинов",
    "application_history": "📝 История заявок",

    "contest_cards": "🖼️ Карточки",
    "contest_full_text": "📄 Положение конкурса",

    "read_the_agreement": "📃 Ознакомиться с текстом согласия",
    "give_agreement": "✅ Даю согласие",
    "refuse_agreement": "❌ Не даю согласие",
    "re_register":"🔄 Пройти регистрацию заново",

    "institute_of_architecture_and_design": "🏛️ Институт архитектуры и дизайна",
    "civil_engineering_institute": "🏗️ Строительный институт",
    "higher_school_of_engineering": "🎓 Высшая инжерная школа EG",
    "higher_school_of_digital_technologies": "💻 Высшая школа цифровых технологий",
    "oil_and_gas_institute": "🛢️ Нефтегазовый институт",
    "institute_of_service_and_industry_management": "💼 Институт сервиса и отраслевого управления",
    "institute_of_technology": "🔧 Технологический институт",
    "institute_of_correspondence_and_distance_education": "📧 Институт заочного и дистанционного образования",

    "topic_social_design": "👨‍👩‍👧‍👧 Социальное проектирование",
    "topic_research_technologies": "🧪 Научно-исследовательские технологии",
    "topic_search_rescue_military": "🚁 Поисково-спасательная и военная деятельность",
    "topic_entrepreneurship": "💼 Предпринимательство",
    "topic_patriotism_history": "🎖 Патриотизм и историческая память",
    "topic_intellectual_games": "📚 Интеллектуальные игры",
    "topic_tiu_competence_center": "🏛 Центр компетенций ТИУ",
    "topic_scenic_creativity": "🎭 Сценическое творчество",
    "topic_applied_creativity": "⭐️ Прикладное творчество",
    "topic_media_communications": "🎬 Медиа и коммуникации",
    "topic_volunteering": "📣 Добровольчество и волонтерство",
    "topic_ecology_nature": "⛅️ Экология и охрана природы",
    "topic_sport": "🏆 Спорт",
    "topic_tourism_travel": "🏕 Туризм и путешествия",
    "topic_digital_sport": "🎮 Фиджитал спорт",
    "topic_student_units": "🎓 Студенческие отряды",
    "topic_united_student_council": "❤️ ОСО/Совет общежитий/Профсоюз",
    "topic_headman": "🗣 Старостат",

    "role_spectator":"👂 Зритель/слушатель",
    "role_participant":"🎯 Участник",
    "role_finalist":"🥈 Финалист/призёр",
    "role_winner":"🏆 Победитель",
    "role_volunteer":"🤝 Волонтёр/помощник",
    "role_coorganizer":"🤲 Соорганизатор",
    "role_organizer":"📋 Организатор",
    "role_mentor":"💡 Наставник/куратор",
    "role_speaker":"🎤 Спикер/эксперт/член жюри",
    "role_leader":"👑 Руководитель/лидер/староста/командир",
    
    "add_more_material":"➕ Добавить еще материал",
    "finish_application":"✅ Завершить заполнение заявки",

    "confirm_application": "✅ Отправить заявку",
    "edit_application": "✏️ Изменить данные",

    "edit_direction_of_activities": "✏️ Изменить направление внеучебной деятельности",
    "edit_event_name" : "✏️ Изменить название мероприятия",
    "edit_event_date": "✏️ Изменить дату мероприятия",
    "edit_event_location": "✏️ Изменить локацию мероприятия",
    "edit_role": "✏️ Изменить роль",
    "edit_confirmation_material": "✏️ Изменить материал, подтверждающий участие",

    "save_registration_form":"✅ Отправить анкету",
    "change_registration_form":"✏️ Изменить данные",

    "full_name":"✏️ Изменить ФИО",
    "institute":"✏️ Изменить структурное подразделение обучения",
    "direction":"✏️ Изменить направление",
    "course":"✏️ Изменить курс",
    "group":"✏️ Изменить группу",
    "start_year":"✏️ Изменить год начала обучения",
    "end_year":"✏️ Изменить год окончания обучения",
    "phone_number":"✏️ Изменить номер телефона",
    "email":"✏️ Изменить почту",

    "select_item": "✅ Выбрать этот товар",
    "back_to_catalog": "⬅️ Назад к каталогу",
    "close_item": "❌ Закрыть",

    "confirm_purchase": "✅ Да, подтверждаю",
    "cancel_purchase": "❌ Нет, отменить",

    "support_write_moderator_of_the_direct":"Обратиться к модератору направления",
    "support_feedback":"Обратная связь",
    "support_error":"Сообщить об ошибке"
}