LEXICON_USER_KEYBOARD = {
    "submit_application": "📝 Подать заявку",
    "my_tyuiu_coins": "💎 Мои ТИУкоины",
    "catalog_of_rewards": "📖 Каталог поощрений",
    "agreement_of_contest": "📃 Положение конкурса",
    "support": "❓ Поддержка",

    "read_the_agreement": "📃 Ознакомиться с текстом согласия",
    "give_agreement": "✅ Даю согласие",
    "refuse_agreement": "❌ Не даю согласие",

    "institute_of_architecture_and_design": "🏛️ Институт архитектуры и дизайна",
    "civil_engineering_institute": "🏗️ Строительный институт",
    "higher_school_of_engineering": "🎓 Высшая инжерная школа EG",
    "higher_school_of_digital_technologies": "💻 Высшая школа цифровых технологий",
    "oil_and_gas_institute": "🛢️ Нефтегазовый институт",
    "institute_of_service_and_industry_management": "💼 Институт сервиса и отраслевого управления",
    "institute_of_technology": "🔧 Технологический институт",
    "institute_of_correspondence_and_distance_education": "📧 Институт заочного и дистанционного образования",

    "topic_social_design": "👨‍👩‍👧‍👧 Социальное проектирование",
    "topic_research_technologies": "🧪 Научно-исследовательские технологии",
    "topic_search_rescue_military": "🚁 Поисково-спасательная и военная деятельность",
    "topic_entrepreneurship": "💼 Предпринимательство",
    "topic_patriotism_history": "🎖 Патриотизм и историческая память",
    "topic_intellectual_games": "📚 Интеллектуальные игры",
    "topic_tiu_competence_center": "🏛 Центр компетенций ТИУ",
    "topic_scenic_creativity": "🎭 Сценическое творчество",
    "topic_applied_creativity": "⭐️ Прикладное творчество",
    "topic_media_communications": "🎬 Медиа и коммуникации",
    "topic_volunteering": "📣 Добровольческо и волонтерство",
    "topic_ecology_nature": "⛅️ Экология и охрана природы",
    "topic_sport": "🏆 Спорт",
    "topic_tourism_travel": "🏕 Туризм и путешествия",
    "topic_digital_sport": "🎮 Фиджитал спорт",
    "topic_student_units": "🎓 Студенческие отряды",
    "topic_united_student_council": "❤️ Объединенный совет обучающихся",
    "topic_headman": "🗣 Старостат",

    "role_spectator":"👂 Зритель/слушатель",
    "role_participant":"🎯 Участник",
    "role_finalist":"🥈 Финалист/призёр",
    "role_winner":"🏆 Победитель",
    "role_volunteer":"🤝 Волонтёр/помощник",
    "role_coorganizer":"🤲 Соорганизатор",
    "role_organizer":"📋 Организатор",
    "role_mentor":"👨‍🏫 Наставник/куратор",
    "role_speaker":"🎤 Спикер/эксперт/член жюри",
    "role_leader":"👑 Руководитель/лидер/староста/командир",

    "confirm_application": "✅ Подтвердить заявку",
    "edit_application": "✏️ Изменить данные",

    "edit_direction_of_activities": "✏️ Изменить направление внеучебной деятельности",
    "edit_event_details": "✏️ Изменить данные о мероприятии",
    "edit_role": "✏️ Изменить роль",
    "edit_confirmation_material": "✏️ Изменить материал, подтверждающий участие",

    "item_pencil": "✏️ Карандаш",
    "item_sticker_pack": "📜 Стикерпак",
    "item_notebook": "📓 Блокнот",
    "item_shopper": "🛍️ Шоппер",
    "item_sweatshirt" : "🧥 Свитшот",
    "item_olympia_course": "🏆 Курс «Олимпия»",

    "save_registration_form":"✅ Сохранить анкету",
    "change_registration_form":"❌ Изменить данные",

    "full_name":"Изменить ФИО",
    "institute":"Изменить институт",
    "direction":"Изменить направление",
    "form_of_education":"Изменить форму образования",
    "course":"Изменить курс",
    "group":"Изменить группу",
    "start_year":"Изменить дату начала",
    "end_year":"Изменить дату конца",
    "phone_number":"Изменить номер телефона",
    "email":"Изменить почту",

    "support_":"Написать модератору направления",
    "":"Посмотреть FAQ",
    "":"Обратная связь"
}